### PR TITLE
rename /var/backup/xivo to wazo

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
recheck

**Comment by fouille** [comment]
@fblackburn1 In file `debian/wazo-backup.postinst` why use `-p` argument (line 10) ? 
When this section run he delete all tree structure and when new backup arrived there are no more folder.

**Comment by fblackburn1** [comment]
> @fblackburn1 In file `debian/wazo-backup.postinst` why use `-p` argument (line 10) ? When this section run he delete all tree structure and when new backup arrived there are no more folder.

New backup will be done in `/var/backups/wazo` and no further backup should be done in `/var/backups/xivo`

**Comment by fblackburn1** [comment]
> > @fblackburn1 In file `debian/wazo-backup.postinst` why use `-p` argument (line 10) ? When this section run he delete all tree structure and when new backup arrived there are no more folder.
> 
> New backup will be done in `/var/backups/wazo` and no further backup should be done in `/var/backups/xivo`

Fixed by https://github.com/wazo-platform/wazo-backup/pull/12

**Pull request merged**
